- name: test raw module
  hosts: 10.0.69.110
  tasks:
    - name: run a powershell script
      script: scripts/test.ps1
      ##script: scripts/helloworld.ps1
      register: out
    - debug: var=out
