---
# This playbook tests the script module on Windows hosts

- name: Run powershell script
  hosts: all 
  gather_facts: false
  tasks:
    - win_shell: echo %HOMEDIR%
  args:
    executable: cmd
  register: homedir_out
